# pokepocketsim/cards_db.py
from typing import Dict, Any
from .cards_enum import Cards
from .energy_type import EnergyType
from .ability import Ability

CARDS_DICT: Dict[Cards, Dict[str, Any]] = {
    # --- Pokémon ---
    Cards.MEWTWO_EX: {
        "name": "ミュウツーEX",
        "hp": 150,
        "type": EnergyType.PSYCHIC,
        "attacks": ["psydrive", "psychic_sphere"],
        "retreat_cost": 2,
        "ability": None,
        "weakness": EnergyType.FIGHTING,
        "is_basic": True,
        "is_ex": True,
        "evolves_from": None,
    },
    Cards.RALTS: {
        "name": "ラルトス",
        "hp": 60,
        "type": EnergyType.PSYCHIC,
        "attacks": ["ram"],
        "retreat_cost": 1,
        "ability": None,
        "weakness": EnergyType.DARK,
        "is_basic": True,
        "is_ex": False,
        "evolves_from": None,
    },
    Cards.KIRLIA: {
        "name": "キルリア",
        "hp": 80,
        "type": EnergyType.PSYCHIC,
        "attacks": ["smack"],
        "retreat_cost": 1,
        "ability": None,
        "weakness": EnergyType.DARK,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": Cards.RALTS,
    },

    Cards.MONMEN: {
        "name": "モンメン",
        "hp": 60,
        "type": EnergyType.GRASS,
        "attacks": ["suitoru"],
        "retreat_cost": 1,
        "weakness": EnergyType.FIRE,
        "resistance": None,
        "is_basic": True,
        "is_ex": False,
        "evolves_from": None,
    },

    Cards.ERUHUN_EX: {
        "name": "エルフーンex",
        "hp": 230,
        "type": EnergyType.GRASS,
        "attacks": ["energy_gift", "wonder_cotton"],
        "retreat_cost": 0,
        "weakness": EnergyType.FIRE,
        "resistance": None,
        "is_basic": None,
        "is_ex": True,
        "evolves_from": Cards.MONMEN,
    },

    Cards.SHIBISHIRASU: {
        "name": "シビシラス",
        "hp": 40,
        "type": EnergyType.LIGHTNING,
        "attacks": ["jittosuru"],
        "retreat_cost": 0,
        "ability": None,
        "weakness": EnergyType.FIGHTING,
        "is_basic": True,
        "is_ex": False,
        "evolves_from": None,
    }, 

    Cards.SHIBIBIRU: {
        "name": "シビビール",
        "hp": 90,
        "type": EnergyType.LIGHTNING,
        "attacks": ["raitoninnguboru"],
        "retreat_cost": 2,
        "ability": Ability.ElekiDynamo(),
        "weakness": EnergyType.FIGHTING,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": Cards.SHIBISHIRASU,
    },

    Cards.EMONGA: {
        "name": "エモンガ",
        "hp": 70    ,
        "type": EnergyType.LIGHTNING,
        "attacks": ["nakamawoyobu", "batibati"],
        "retreat_cost": 0,
        "ability": None,
        "weakness": EnergyType.FIGHTING,
        "is_basic": True,
        "is_ex": False,
        "evolves_from": None,
    }, 

    Cards.TERAKION: {
        "name": "テラキオン",
        "hp": 140    ,
        "type": EnergyType.FIGHTING,
        "attacks": ["katakiuti", "randkurasshu"],
        "retreat_cost": 3,
        "ability": None,
        "weakness": EnergyType.GRASS,
        "is_basic": True,
        "is_ex": False,
        "evolves_from": None,
    }, 

    Cards.ZEKROM_EX: {
        "name": "ゼクロムex",
        "hp": 230,
        "type": EnergyType.LIGHTNING,
        "attacks": ["slash", "voltage_burst"],
        "retreat_cost": 2,
        "ability": None,
        "weakness": EnergyType.FIGHTING,
        "resistance": None,
        "is_basic": True,
        "is_ex": True,
        "evolves_from": None,
    },

    # --- Trainer / Goods ---
    Cards.ULTRA_BALL: {
        "name": "ハイパーボール",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_item": True,
        "trainer_text": "手札を2枚トラッシュする。その後、山札からポケモンを1枚選び、手札に加える。",
    },
    Cards.POKEMON_CATCHER: {
        "name": "ポケモンキャッチャー",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_item": True,
        "trainer_text": "コインを1回投げオモテなら、相手のベンチポケモンを1匹選び、バトルポケモンと入れ替える。",
    },

    Cards.SWITCH: {
        "name": "ポケモンいれかえ",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_item": True,
        "trainer_text": "自分のバトルポケモンをベンチポケモンと入れ替える。",
    },

    Cards.POKEGEAR3_0: {
        "name": "ポケギア3.0",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_item": True,
        "trainer_text": "自分の山札を上から7枚見て、その中からサポートを1枚選び、相手に見せて、手札に加える。残りのカードは山札にもどしてシャッフルする。",
    },

    Cards.CRUSHING_HAMMER: {
        "name": "クラッシュハンマー",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_item": True,
        "trainer_text": "コインを1回投げ、オモテなら相手の場のポケモンについているエネルギーを1個選び、トラッシュする。バトル場・ベンチどちらでもOK。相手の場にエネルギーが1枚もない場合は使えない（トラッシュもされない）。",
    },

    Cards.BALLOON: {
        "name": "ふうせん",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_tool": True,
        "trainer_text": "このカードをつけているポケモンは、にげるためのエネルギーが2個ぶん少なくなる。",
    },

# -------- サポート --------
    Cards.NANJAMO: {
        "name": "ナンジャモ",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_supporter": True,
        "trainer_text": "お互いの手札を山札の下に戻して切り、その後自分の残りサイドの枚数ぶん引く。",
    },

    Cards.BOSS_ORDERS: {
        "name": "ボスの指令",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_supporter": True,
        "trainer_text": "相手のベンチポケモンを1匹選び、バトルポケモンと入れ替える。",
    },

    Cards.PROFESSORS_RESEARCH: {
        "name": "博士の研究",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_supporter": True,
        "trainer_text": "手札を全てトラッシュする。その後、山札から7枚カードを引く。",
    },

    Cards.CROWN: {
        "name": "クラウン",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_supporter": True,
        "trainer_text": "おたがいのプレイヤーは、それぞれ手札をすべて山札にもどしてシャッフルする。その後、自分はコインを1回投げる。オモテなら自分は5枚、相手は3枚、山札から引く。ウラなら自分は3枚、相手は5枚、山札から引く。",
    },

    Cards.CHEREN: {
        "name": "チェレン",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_supporter": True,
        "trainer_text": "自分の山札を3枚引く。",
    },

    Cards.TOUKO: {
        "name": "トウコ",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_supporter": True,
        "trainer_text": "自分の山札を3枚引く。",
    },

    Cards.MAKOMO: {
        "name": "マコモ",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_supporter": True,
        "trainer_text": "自分の山札を3枚引く。",
    },
    Cards.BOWL_TOWN: {
        "name": "ボウルタウン",
        "hp": None,
        "type": None,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": True,
        "is_stadium": True,
        "trainer_text": "おたがいのプレイヤーは、自分の番ごとに1回、自分の山札からたねポケモン（「ルールを持つポケモン」をのぞく）を1枚選び、ベンチに出してよい。そして山札を切る。",
    },

    Cards.GRASS_ENERGY: {
        "name": "草エネルギー",
        "hp": None,
        "type": EnergyType.GRASS,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": False,
        "trainer_text": None,
        "is_energy": True,
        "is_basic_energy": True,
    },

    Cards.FIRE_ENERGY: {
        "name": "炎エネルギー",
        "hp": None,
        "type": EnergyType.FIRE,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": False,
        "trainer_text": None,
        "is_energy": True,
        "is_basic_energy": True,
    },

    Cards.WATER_ENERGY: {
        "name": "水エネルギー",
        "hp": None,
        "type": EnergyType.WATER,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": False,
        "trainer_text": None,
        "is_energy": True,
        "is_basic_energy": True,
    },

    Cards.LIGHTNING_ENERGY: {
        "name": "雷エネルギー",
        "hp": None,
        "type": EnergyType.LIGHTNING,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": False,
        "trainer_text": None,
        "is_energy": True,
        "is_basic_energy": True,
    },

    Cards.PSYCHIC_ENERGY: {
        "name": "超エネルギー",
        "hp": None,
        "type": EnergyType.PSYCHIC,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": False,
        "trainer_text": None,
        "is_energy": True,
        "is_basic_energy": True,
    },

    Cards.FIGHTING_ENERGY: {
        "name": "闘エネルギー",
        "hp": None,
        "type": EnergyType.FIGHTING,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": False,
        "trainer_text": None,
        "is_energy": True,
        "is_basic_energy": True,
    },

    Cards.DARK_ENERGY: {
        "name": "悪エネルギー",
        "hp": None,
        "type": EnergyType.DARK,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": False,
        "trainer_text": None,
        "is_energy": True,
        "is_basic_energy": True,
    },

    Cards.METAL_ENERGY: {
        "name": "鋼エネルギー",
        "hp": None,
        "type": EnergyType.METAL,
        "attacks": [],
        "retreat_cost": 0,
        "ability": None,
        "weakness": None,
        "is_basic": False,
        "is_ex": False,
        "evolves_from": None,
        "is_trainer": False,
        "trainer_text": None,
        "is_energy": True,
        "is_basic_energy": True,
    },

}
